### ISSUE TITLE
fix: error with issue_comment event

### ISSUE THREAD

**Issue by Elph** [Elph/duckbot#18]
As this event does not has any pull_request object, it throws an exception

```
TypeError: Cannot read property 'head' of undefined
      at setYoutrackRepoCommands (/var/task/src/pipeline/setYouTrackRepoCommands.js:2:31)
      at /var/task/node_modules/pipeline-js/index.js:54:25
      at Array.forEach (<anonymous>)
      at Pipeline.process (/var/task/node_modules/pipeline-js/index.js:44:12)
      at app.on (/var/task/src/app.js:38:20)
      at Application.<anonymous> (/var/task/node_modules/probot/lib/application.js:153:50)
      at step (/var/task/node_modules/probot/lib/application.js:43:23)
      at Object.next (/var/task/node_modules/probot/lib/application.js:24:53)
      at fulfilled (/var/task/node_modules/probot/lib/application.js:15:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Elph** [comment]
We should remove the issue_comment from the incoming events
